mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^timeline/', include('timeline.urls', namespace='timeline')),
    url(r'^admin/', include(admin.site.urls)),
]

timeline/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^get_input/$', views.get_input, name='get_input'),
    url(r'^result/$', views.result, name='result'),
    url(r'^show_tweets/$', views.show_tweets, name='show_tweets'),
]

timeline/models.py
from django.db import models


class User(models.Model):
    """ a twitter user handle """
    scr_name = models.CharField(max_length=20)

    def __str__(self):
        return self.scr_name


class Tweet(models.Model):
    """ a user's tweet """
    user = models.ForeignKey(User)
    tweet_text = models.CharField(max_length=200)

    def __str__(self):
        return str(self.user) + ': ' + self.tweet_text

timeline/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from tweets import extract_tweets, get_tweets, get_stats, remove_self
from tweets import get_hash_mentions
from .models import User, Tweet


MAX_TWEET = 3200

def index(request):
    return HttpResponse("Hello, world. You're at timeline site.")


def get_input(request):
    return render(request, 'timeline/get_input.html')


def result(request, tweets, hash_tags, mentions):
    context =  {'tweets': tweets, 'hash_tags': hash_tags, 'mentions': mentions}
    return render(request, 'timeline/result.html', context)


def show_tweets(request):
    scr_name= request.POST.get("screen_name")
    twt_count = int(request.POST.get("tweet_count"))
    stat_count = int(request.POST.get("stat_count"))
    try:
        user = User.objects.get(scr_name=scr_name)
        tweets = [tweet.tweet_text for tweet in user.tweet_set.all()]
        hash_tags, mentions = get_hash_mentions(tweets[:twt_count], stat_count)
        tweets = tweets[:twt_count]
        return result(request, tweets, hash_tags, mentions)
    except User.DoesNotExist:
        tweets = get_tweets(scr_name, MAX_TWEET)
        if 'error' in tweets:
            retry = '<br><a href="/timeline/get_input">Try another user!</a>'
            return HttpResponse(tweets['error']+retry)
        tweets = extract_tweets(tweets)
        user = User(scr_name=scr_name)
        user.save()
        for tweet in tweets:
            user.tweet_set.create(tweet_text=tweet)
        hash_tags, mentions = get_hash_mentions(tweets[:twt_count], stat_count)
    return result(request, tweets[:twt_count], hash_tags, mentions)

timeline/templates/timeline/get_input.html
<h1>Enter the details<h1>

<form action="{% url 'timeline:show_tweets' %}" method="post">
{% csrf_token %}
    <p>twitter screen name</p>
    <input type="text" name="screen_name">
    <p>number of tweets to display</p>
    <input type="text" name="tweet_count">
    <p>number of stats to display</p>
    <input type="text" name="stat_count">
    <p><input type="submit" value="Get_timeline" /></p>
</form>

timeline/templates/timeline/result.html
<h1> TimeLine </h1>
{% if tweets%}
    <ol>
    {% for tweet in tweets %}
        <li>{{tweet}}</li><br>
    {% endfor %}
    </ol>
{% else %}
    <p>No result are available.</p>
{% endif %}

<h1> Most used hashtags</h1>
{% if hash_tags%}
    <ol>
    {% for hash_tag in hash_tags%}
        <li>{{hash_tag.0}} {{hash_tag.1}} times</li>
    {% endfor %}
    </ol>
{% else %}
    <p>No hashtags used!.</p>
{% endif %}

<h1> Most mentioned users </h1>
{% if mentions%}
    <ol>
    {% for mention in mentions %}
        <li>{{mention.0}} {{mention.1}} times</li>
    {% endfor %}
    </ol>
{% else %}
    <p>No user mentions!.</p>
{% endif %}

<a href="{% url 'timeline:get_input' %}">Try Another User!</a> 